import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import StoreNavbar from "@/app/components/StoreNavbar";
import Footer from "@/app/components/Footer";

type OrderPageProps = { params: Promise<{ id: string }> };

export default async function OrderPage({ params }: OrderPageProps) {
  const session = await auth();
  if (!session?.user?.id) redirect("/login?callbackUrl=/orders");
  const { id } = await params;
  const order = await prisma.order.findUnique({ where: { id }, include: { items: true } });
  if (!order) notFound();
  if (order.userId !== session.user.id) redirect("/orders");
  const statusSteps = ["PENDING", "PROCESSING", "SHIPPED", "DELIVERED"];
  const currentIndex = statusSteps.indexOf(order.status);

  return <main className="min-h-screen bg-espresso text-offwhite"><StoreNavbar /><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8 lg:py-16"><Link href="/orders" className="text-xs uppercase tracking-widest text-gold">← Back to orders</Link><div className="mt-8 flex flex-col gap-5 border-b border-bronze/30 pb-10 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[.25em] text-gold">Order confirmed</p><h1 className="mt-3 font-playfair text-5xl">Thank you.</h1><p className="mt-3 text-sm text-warmgrey">Order #{order.id}</p></div><span className="w-fit rounded-full border border-gold/50 px-4 py-2 text-xs uppercase tracking-widest text-gold">{order.status}</span></div>
    <section className="mt-8 rounded-2xl border border-bronze/30 bg-charcoal/50 p-6 sm:p-8"><p className="text-xs uppercase tracking-[.2em] text-gold">Delivery progress</p><div className="mt-8 grid grid-cols-4 gap-2">{statusSteps.map((step,index) => <div key={step}><div className={`h-1 rounded-full ${currentIndex >= index ? "bg-gold" : "bg-bronze/30"}`} /><p className={`mt-3 text-[10px] uppercase tracking-widest ${currentIndex >= index ? "text-gold" : "text-warmgrey"}`}>{step}</p></div>)}</div></section>
    <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_340px]"><section className="rounded-2xl border border-bronze/30 bg-charcoal/50 p-6 sm:p-8"><p className="text-xs uppercase tracking-[.2em] text-gold">Items</p><div className="mt-5 divide-y divide-bronze/20">{order.items.map(item => <div key={item.id} className="flex justify-between gap-5 py-5"><div><p className="font-playfair text-xl">{item.productName}</p><p className="mt-1 text-xs text-warmgrey">{item.variantName} · Qty {item.quantity}</p><p className="mt-2 text-xs text-warmgrey">PKR {Number(item.price).toFixed(2)} each</p></div><p className="text-sm">PKR {(Number(item.price)*item.quantity).toFixed(2)}</p></div>)}</div><div className="mt-5 space-y-3 border-t border-bronze/20 pt-5 text-sm"><div className="flex justify-between text-warmgrey"><span>Subtotal</span><span>PKR {Number(order.subtotal).toFixed(2)}</span></div>{Number(order.discount)>0&&<div className="flex justify-between text-gold"><span>Discount</span><span>-PKR {Number(order.discount).toFixed(2)}</span></div>}<div className="flex justify-between text-warmgrey"><span>Shipping</span><span>{Number(order.shippingCost)===0 ? "Free" : `PKR ${Number(order.shippingCost).toFixed(2)}`}</span></div><div className="flex justify-between border-t border-bronze/20 pt-4 text-xl"><span>Total</span><span>PKR {Number(order.total).toFixed(2)}</span></div></div></section><aside className="h-fit space-y-5"><div className="rounded-2xl border border-bronze/30 bg-charcoal/50 p-6"><p className="text-xs uppercase tracking-[.2em] text-gold">Order details</p><div className="mt-5 space-y-4 text-sm"><div><p className="text-xs text-warmgrey">Payment</p><p className="mt-1">{order.paymentMethod === "COINS" ? "Niivora Coins" : "Cash on Delivery"}</p></div><div><p className="text-xs text-warmgrey">Payment status</p><p className="mt-1">{order.paymentStatus}</p></div><div><p className="text-xs text-warmgrey">Placed</p><p className="mt-1">{order.createdAt.toLocaleDateString()}</p></div></div></div><div className="rounded-2xl border border-bronze/30 bg-charcoal/50 p-6"><p className="text-xs uppercase tracking-[.2em] text-gold">Delivery</p><p className="mt-4 text-sm">{order.customerName}</p><p className="mt-1 text-sm text-warmgrey">{order.shippingAddress}</p><p className="text-sm text-warmgrey">{order.shippingCity}{order.shippingPostalCode ? `, ${order.shippingPostalCode}` : ""}</p></div></aside></div><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="rounded-xl bg-gold px-6 py-3 text-xs font-semibold uppercase tracking-widest text-espresso">Continue shopping</Link><Link href="/account" className="rounded-xl border border-gold px-6 py-3 text-xs font-semibold uppercase tracking-widest text-gold">My account</Link></div></div><Footer /></main>;
}
