"use client";
import { useEffect, useState } from "react";

type Withdrawal = { id:string; amount:number; bankName:string; accountNumber:string; status:string; createdAt:string; adminNote:string|null; user:{name:string|null;email:string|null;founderCode:string|null} };
export default function AdminWithdrawalsPage(){
 const [rows,setRows]=useState<Withdrawal[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 async function load(){try{const r=await fetch("/api/admin/withdrawals");const d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.withdrawals)}catch(e){setError(e instanceof Error?e.message:"Unable to load withdrawals.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function process(id:string,status:"COMPLETED"|"REJECTED"){if(status==="COMPLETED"&&!confirm("Confirm that you transferred these funds to the founder's bank account?"))return;try{const r=await fetch("/api/admin/withdrawals",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to process withdrawal.")}}
 return <main className="min-h-screen bg-[#1a1512] px-5 py-10 text-[#f5f1ea] sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm uppercase tracking-[.25em] text-[#c6a15b]">Finance</p><h1 className="mt-2 font-playfair text-5xl">Withdrawals</h1><p className="mt-2 text-[#9c8f7c]">Review founder withdrawal requests and record manual bank transfers.</p>{error&&<div className="mt-6 rounded-xl border border-red-900 bg-red-950/30 p-4 text-red-300">{error}</div>}<div className="mt-8 overflow-hidden rounded-2xl border border-[#3a3027] bg-[#211b17]"><div className="overflow-x-auto">{loading?<p className="p-8 text-[#9c8f7c]">Loading...</p>:<table className="w-full min-w-[900px]"><thead className="border-b border-[#3a3027] text-left text-xs uppercase tracking-wider text-[#9c8f7c]"><tr><th className="p-5">Founder</th><th className="p-5">Amount</th><th className="p-5">Bank</th><th className="p-5">Account</th><th className="p-5">Status</th><th className="p-5">Action</th></tr></thead><tbody>{rows.map(w=><tr key={w.id} className="border-b border-[#3a3027] last:border-0"><td className="p-5"><p>{w.user.name??"Unnamed"}</p><p className="text-sm text-[#9c8f7c]">{w.user.email} · {w.user.founderCode}</p></td><td className="p-5 font-medium text-[#c6a15b]">PKR {w.amount.toFixed(2)}</td><td className="p-5">{w.bankName}</td><td className="p-5 font-mono">{w.accountNumber}</td><td className="p-5">{w.status}</td><td className="p-5">{w.status==="PENDING"?<div className="flex gap-2"><button onClick={()=>process(w.id,"COMPLETED")} className="rounded-lg bg-[#c6a15b] px-3 py-2 text-sm text-[#1a1512]">Mark Paid</button><button onClick={()=>process(w.id,"REJECTED")} className="rounded-lg border border-[#3a3027] px-3 py-2 text-sm">Reject</button></div>:<span className="text-sm text-[#9c8f7c]">Processed {new Date(w.createdAt).toLocaleDateString()}</span>}</td></tr>)}{!rows.length&&<tr><td colSpan={6} className="p-10 text-center text-[#9c8f7c]">No withdrawal requests.</td></tr>}</tbody></table>}</div></div></div></main>;
}
