import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import Link from "next/link";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

export default async function OrdersPage() {
  const session = await auth();
  if (!session?.user?.id) redirect("/login?callbackUrl=/orders");
  const orders = await prisma.order.findMany({ where: { userId: session.user.id }, include: { items: true }, orderBy: { createdAt: "desc" } });
  return <main className="min-h-screen bg-espresso text-offwhite"><Navbar isAuthenticated isAdmin={session.user.role === "ADMIN"} isFounder={session.user.customerType === "FOUNDER"} /><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8 lg:py-16"><div className="mb-10"><p className="text-xs uppercase tracking-[.25em] text-gold">Your account</p><h1 className="mt-3 font-playfair text-5xl">My orders.</h1><p className="mt-3 text-sm text-warmgrey">Every order, status and delivery detail in one place.</p></div>{orders.length === 0 ? <div className="rounded-2xl border border-bronze/30 bg-charcoal/50 px-6 py-20 text-center"><p className="text-xs uppercase tracking-[.2em] text-gold">Nothing here yet</p><h2 className="mt-3 font-playfair text-3xl">Your first ritual awaits.</h2><Link href="/products" className="mt-7 inline-block rounded-xl bg-gold px-7 py-3 text-xs font-semibold uppercase tracking-widest text-espresso">Shop Niivora</Link></div> : <div className="space-y-5">{orders.map(order => <article key={order.id} className="overflow-hidden rounded-2xl border border-bronze/30 bg-charcoal/50"><div className="flex flex-col gap-4 border-b border-bronze/20 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-warmgrey">Order #{order.id.slice(-8).toUpperCase()}</p><p className="mt-2 text-sm text-offwhite/70">{order.createdAt.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p></div><div className="flex gap-2"><span className="rounded-full border border-bronze/40 px-3 py-1.5 text-[10px] uppercase tracking-widest text-gold">{order.status}</span><span className="rounded-full border border-bronze/40 px-3 py-1.5 text-[10px] uppercase tracking-widest text-offwhite/70">{order.paymentStatus}</span></div></div><div className="divide-y divide-bronze/20">{order.items.slice(0, 3).map(item => <div key={item.id} className="flex items-center justify-between gap-4 px-6 py-4"><div><p className="text-sm">{item.productName}</p><p className="mt-1 text-xs text-warmgrey">{item.variantName} · Qty {item.quantity}</p></div><p className="text-sm">PKR {(Number(item.price) * item.quantity).toFixed(2)}</p></div>)}</div><div className="flex items-center justify-between border-t border-bronze/20 p-6"><div><p className="text-xs uppercase tracking-widest text-warmgrey">Total</p><p className="mt-1 text-xl font-medium">PKR {Number(order.total).toFixed(2)}</p></div><Link href={`/orders/${order.id}`} className="rounded-xl border border-gold px-5 py-3 text-xs font-semibold uppercase tracking-widest text-gold transition hover:bg-gold hover:text-espresso">View order</Link></div></article>)}</div>}</div><Footer /></main>;
}
