"use client";
import { useState } from "react";
import { PAKISTANI_BANKS } from "@/lib/pakistani-banks";

export default function WithdrawalForm({ balance }: { balance: number }) {
  const [amount, setAmount] = useState(""); const [bankName, setBankName] = useState(""); const [accountNumber, setAccountNumber] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setMessage(""); try { const res = await fetch("/api/founder/withdrawals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amount, bankName, accountNumber }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setMessage("Withdrawal request submitted successfully."); setAmount(""); setBankName(""); setAccountNumber(""); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to submit request."); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="mt-8 border-t border-[#3a3027] pt-7"><h3 className="font-playfair text-2xl">Withdraw coins</h3><p className="mt-1 text-sm text-[#9c8f7c]">Available: {balance.toFixed(2)} NC / PKR</p><div className="mt-5 space-y-4"><input type="number" min="1" max={balance} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount of coins" required className="w-full rounded-xl border border-[#3a3027] bg-[#1a1512] px-4 py-3 text-[#f5f1ea] outline-none"/><select value={bankName} onChange={e=>setBankName(e.target.value)} required className="w-full rounded-xl border border-[#3a3027] bg-[#1a1512] px-4 py-3 text-[#f5f1ea] outline-none"><option value="">Select Pakistani bank</option>{PAKISTANI_BANKS.map(bank=><option key={bank} value={bank}>{bank}</option>)}</select><input inputMode="numeric" value={accountNumber} onChange={e=>setAccountNumber(e.target.value.replace(/\D/g,""))} placeholder="Bank account number" required className="w-full rounded-xl border border-[#3a3027] bg-[#1a1512] px-4 py-3 text-[#f5f1ea] outline-none"/><button disabled={loading || balance <= 0} className="w-full rounded-xl bg-[#c6a15b] px-5 py-3 font-medium text-[#1a1512] disabled:opacity-50">{loading ? "Submitting..." : "Request Withdrawal"}</button></div>{message && <p className="mt-4 text-sm text-[#c6a15b]">{message}</p>}</form>;
}
