import { prisma } from "@/lib/prisma";
import Link from "next/link";
import StoreNavbar from "@/app/components/StoreNavbar";
import Footer from "@/app/components/Footer";

export default async function ProductsPage() {
  const products = await prisma.product.findMany({ where: { active: true }, include: { variants: { orderBy: { createdAt: "asc" } } }, orderBy: { createdAt: "desc" } });
  return <main className="min-h-screen bg-espresso text-offwhite"><StoreNavbar /><div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 lg:py-16"><div className="mb-12 max-w-2xl"><p className="text-xs uppercase tracking-[.25em] text-gold">The collection</p><h1 className="mt-3 font-playfair text-5xl sm:text-6xl">Care, made ritual.</h1><p className="mt-4 text-sm leading-7 text-warmgrey">Explore Niivora's current collection of botanical hair care, thoughtfully formulated for stronger roots and healthier hair.</p></div>{products.length === 0 ? <div className="rounded-2xl border border-bronze/30 bg-charcoal/50 p-16 text-center text-warmgrey">No products available.</div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(product => { const variants = product.variants; const prices = variants.map(v => Number(v.price)); const lowest = Math.min(...prices); const highest = Math.max(...prices); const stock = variants.reduce((sum,v) => sum + v.stock,0); return <Link key={product.id} href={`/products/${product.slug}`} className="group overflow-hidden rounded-2xl border border-bronze/30 bg-charcoal/50 transition duration-300 hover:-translate-y-1 hover:border-gold/60"><div className="aspect-[4/4.5] overflow-hidden bg-espresso">{product.image ? <img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-sm text-warmgrey">No Image</div>}</div><div className="p-6"><div className="flex items-start justify-between gap-4"><h2 className="font-playfair text-2xl">{product.name}</h2>{product.featured && <span className="text-[9px] uppercase tracking-widest text-gold">Featured</span>}</div><p className="mt-2 text-sm text-warmgrey">{product.description ?? "Natural care for your everyday ritual."}</p><p className="mt-5 text-sm">{lowest === highest ? `PKR ${lowest.toFixed(2)}` : `PKR ${lowest.toFixed(2)} – ${highest.toFixed(2)}`}</p><p className={`mt-2 text-xs uppercase tracking-widest ${stock > 0 ? "text-gold" : "text-red-300"}`}>{stock > 0 ? `${variants.length} option${variants.length > 1 ? "s" : ""} available` : "Out of stock"}</p></div></Link> })}</div>}</div><Footer /></main>;
}
